host:
  address: ""

portainer:
  address: ""
  port: 9443

email:
  name: "Docker Watchdog"
	sender: ""
	password: ""
  subject: "Docker Watchdog - Stopped Containers Detected (alert)"
	recipients:
		- "anggit@isi.co.id"

smtp:
	server: "smtps.atisicloud.com"
	port: 587
