host:
  address: ""
  portainer_port: 9443

email:
  name: "Docker Watchdog"
	sender: ""
	password: ""
  subject: "Docker Containers Alert - Stopped Containers Detected"
	recipients:
		- "anggit@isi.co.id"

smtp:
	server: "smtps.atisicloud.com"
	port: 587
