# Copyright © 2022 Anggit M Ginanjar <anggit@isi.co.id> from PT Infinys System Indonesia 
#
# VM or Server (or even localhost machine)
host:
  # e.g 127.0.0.1, mydomain.com without protocol scheme like http or https
  # address: "127.0.0.1 (my local)"
  address: "127.0.0.1 - my local"

# Portainer, master address
portainer:
  # e.g 127.0.0.1, portainer.domain.com without protocol scheme like http or https
  # address: "127.0.0.1"
  address: "127.0.0.1"
  port: 9443

# Mail account that used by docker watchdog for sending email to recipients
# e.g Developer or System Administrator
email:
  name: "Docker Watchdog"
  
  # e.g docker@myemail.com
  sender: "docker@myemail.com"
  password: ""
  subject: "Docker Watchdog - Stopped Containers Detected (alert)"

  # Developer or System Administrator's emails
  recipients:
    - "anggit.ginanjar@outlook.com"

# SMTP Server
smtp:
  address: "smtp.gmail.com"
  port: 587
